#!/bin/bash
# genproj
# Copyright (c) 2021 J. M. Spivey

# Geany project files have absolute paths embedded within them, and change
# whenever Geany runs, so they aren't suitable for checking in to version
# control.  This script generates project files in each lab directory from
# prototypes that are under version control, substituting locally
# appropriate values for each @MARKER@ in the prototype.

# $dir is the parent directory of the setup subdirectory in which this
# script lives.
dir="$(dirname $(dirname $(realpath $0)))"

# For each project, substitute project-specific values for each @MARKER@;
# then on the "[files]/FILE_NAME" line, encode / as %2F
project() {
    proj=$1; source=$2
    sed -e "s:@DIR@:$dir:" \
        -e "s:@PROJ@:$proj:" \
        -e "/^FILE_NAME/s:/:%2F:g" \
        "$dir/setup/$source.geany" >"$dir/$proj/$proj.geany"
}

project lab1 proto
project lab2 proto
project lab3 proto
project ppc4 proto
project lab4 lab4
