#!/bin/bash

# Setup script for Compilers.

# Make sure the shell is bash.
if [ x$BASH_VERSION = x ]; then exec /bin/bash $0; fi

cd $(dirname $0)

# Associate project files with Geany
/bin/mkdir -p "$HOME/.local/share/applications" \
           "$HOME/.local/share/mime/packages" "$HOME/.config/geany"
/bin/cp application-x-geany-project.xml "$HOME/.local/share/mime/packages"
/bin/cp geany.desktop "$HOME/.local/share/applications"
update-mime-database "$HOME/.local/share/mime"
update-desktop-database "$HOME/.local/share/applications"

set-option () {
    # Like crudini --set, but without the syntax error in new options
    # or troubles with trailing whitespace
    python3 houdini.py set "$1" "$2" "$3" "$4"
}

geanyconf="$HOME/.config/geany/geany.conf"

# Disable 'Load files from last session'
set-option "$geanyconf" geany pref_main_load_session false

# Turn off annoying beep
set-option "$geanyconf" geany beep_on_errors false

# Enable Project Organiser and GeanyVC
set-option "$geanyconf" plugins load_plugins true
plugins=$(python3 houdini.py get "$geanyconf" plugins active_plugins)
for ext in projectorganizer geanyvc; do
    file=$(find /usr/lib* -name $ext.so -print -quit)
    if [ -r $file ] && ! [[ ";$plugins" =~ ";$file;" ]]; then
        plugins="$plugins$file;"
    fi
done
set-option "$geanyconf" plugins active_plugins "$plugins"

# Select project tab in sidebar
set-option "$geanyconf" geany sidebar_page 2

# Generate project files
/bin/bash genproj

echo "*** Now please log out and log back in again."
